config/routes.rb
Lgp::Application.routes.draw do

  # auth
  resources :authentications, :only=>[:create]
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/:provider' => 'authentications#show'


  # public
  resources :welcome, :only=>[:index]
  resources :invite_codes, :only=>[:create]
  resources :invite_requests, :only=>[:create]

  # user scoped
  devise_for :users
  namespace :users do
    resources :answers, :only => [ :create, :update ]
    resources :dashboards, :only => [ :index, :update ]
    # change message to be resource based route --- not match when implemented.
    #match "/messages" => "messages#message", :as=>"message"
    match 'conversations/update_preferred_theaters' => 'conversations#update_preferred_theaters', :via => [:get, :post]
    resources :conversations, :messages
    match "inbox" => "conversations#index"
    match "sentbox" => "conversations#sent"
    resources :movies, :only => [ :index, :show ]
    resources :photos, :only => [ :index, :create , :update, :destroy ]
    resources :profiles, :only => [ :index, :show, :edit, :update ]
    resources :watch_lists, :only => [ :create, :destroy ]
  end

  # admin scoped
  resources :admin, :only=>[:index]
  namespace :admin do
    resources :invite_codes
    resources :movies
    resources :questions
    resources :schedules
    resources :theaters
    resources :zip_locs
  end

  # default route
  root :to => 'welcome#index'
 
  match ':controller(/:action(/:id))'

end

app/controllers/users/answers_controller.rb
class Users::AnswersController < UsersController

  def create
    a=Answer.new(params[:answer])

    # security -- check user
    unless a.user_id == current_user.id
      render :json => { :success=>false, :errors=>['unauthorized']}
      return
    end

    if a.response.blank?
      render :json => { :success=> true, :question_id=>a.question_id, :new_response=>'' }
    else
      if a.save
        render :json => { :success=> true, :question_id=>a.question_id, :new_response=>a.response }
      else
        render :json => { :success=> false, :errors=>a.errors.to_json }
      end
    end


  end

  def update
    a=Answer.find(params[:id])

    # security -- check user
    unless a.user_id == current_user.id
      render :json => { :success=>false, :errors=>['unauthorized']}
      return
    end

    if params[:answer][:response].blank?
      qid=a.question_id
      a.destroy
      render :json => { :success=> true, :question_id=>qid, :new_response=>'' }
    else
      if a.update_attributes(params[:answer])
        render :json => { :success=> true, :question_id=>a.question_id, :new_response=>a.response }
      else
        render :json => { :success=> false, :errors=>a.errors.to_json }
      end
    end


  end

end

app/controllers/users/conversations_controller.rb
class Users::ConversationsController < UsersController

  before_filter :get_mailbox
  #before_filter :check_current_subject_in_conversation, :only => [:show, :update, :destroy]
  def index
    @conversations = @mailbox.inbox
    @mailbox_type = "inbox"
  end

  def show
    @message = Message.new
    @conversation = Conversation.where("id = ?", params[:id]).first
    @receipts = @conversation.receipts_for(current_user).order("created_at DESC")
    @receipts = remove_duplicate_receipts @receipts
    @recipient =  get_initial_recipient(@conversation)
    # check if there is a subject and therefore a movie title
    if @conversation.subject != "N/A"   #@TODO might want to change this later
      # get the movie object
      movie = Movie.find_by_title(@conversation.subject)
      # get the watchlist
      watch_list = WatchList.where("user_id = ? AND movie_id = ?", @recipient.id, movie.id).first
      #check for preferred theaters
      @preferred_theaters =  @recipient.watch_list_preferred_theaters(watch_list.id)
    end
  end

  def new
    if params[:recipient_id]
      @recipient = User.find_by_id(params[:recipient_id])
      @movies = @recipient.watchlist_movies
      if params[:watch_list_id]
        watch_list_item = WatchList.find(params[:watch_list_id])
        @default_movie = Movie.find(watch_list_item.movie_id)
        @preferred_theaters = @recipient.watch_list_preferred_theaters(watch_list_item.id)
      end
    end
  end

  def edit
    #@TODO if required
  end

  def create
    # verify everything
    recipient = User.find_by_id params[:recipient][:id]
    movie = Movie.find_by_id(params[:movie_id])
    body = params[:body][0]
    #@TODO add check here to make sure everything above is valid before sending message
    # create conversations e.g. send first message
    conversation = @current_user.send_message(recipient, body, movie.nil? ? "N/A" : movie.title )
    # return user to conversations page
    if conversation
      redirect_to users_conversations_path
    end
  end

  def sent
    @conversations = @mailbox.sentbox
    @mailbox_type = "sentbox"
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @conversation = @user.mailbox.conversations.where("conversation_id = ?", params[:format]).first
    @conversation.move_to_trash(@user)
    redirect_to users_inbox_path(@user)
  end

  def reply_to_conversation
    conversation = Conversation.find_by_id(params[:conversation][:id])
    message_sent = current_user.reply_to_conversation(conversation, params[:body][:body])
    if message_sent
      redirect_to users_conversation_path(conversation)
    end
  end

  def update_preferred_theaters
    @recipient = User.find_by_id(params[:user_id])
    watch_list = WatchList.where("user_id = ? AND movie_id = ?", @recipient.id, params[:movie_id]).first
    @preferred_theaters = @recipient.watch_list_preferred_theaters(watch_list.id)
    if @preferred_theaters
      respond_to do |format|
        format.js
      end
    end
  end

  private

  def get_mailbox
    @mailbox = current_user.mailbox
  end

  def get_actor
    @actor = Actor.normalize(current_user)
  end

  def get_box
    if params[:box].blank? or !["inbox","sentbox","trash"].include?params[:box]
      @box = "inbox"
    return
    end
    @box = params[:box]
  end

  def check_current_subject_in_conversation
    @conversation = Conversation.find_by_id(params[:id])

    if @conversation.nil? or !@conversation.is_participant?(@actor)
      redirect_to conversations_path(:box => @box)
    return
    end
  end

  def get_initial_recipient(conversation)
    # get last message receipt
    receipt = conversation.receipts.where("mailbox_type = ?", "inbox").order("created_at DESC").last
    # get receiving user
    user = User.find_by_id(receipt.receiver_id)
  end

  # if the user sends a message to themselves the first message will be repeated in both their inbox and outbox.
  # This removes that duplication.
  def remove_duplicate_receipts receipts
    size = receipts.size
    last = receipts[size-1]
    second_last = receipts[size-2]
    # check if they are the same
    if last.message == second_last.message
      receipts.pop
    end
    receipts
  end
end

app/controllers/users/dashboards_controller.rb
class Users::DashboardsController < UsersController

  def index
    @user=User.find(current_user.id)
    @near_buddies = @user.near_buddies
    @popular_movies = Movie.popular(@user.zipcode)
  end

  # processes second registration step for user
  def update
    @user=User.find(params[:id])

    # security check
    unless @user.id==current_user.id
      @user.errors[:firstname] << 'you do not have permission to do this'
      return
    end

    # fields we are allowed to update, with custom errors if not present...
    if params[:user][:firstname] && !params[:user][:firstname].blank?
      @user.firstname=params[:user][:firstname]
    else
      @user.errors[:firstname] << 'is required.'
    end

    if params[:user][:gender] && !params[:user][:gender].blank?
      @user.gender=params[:user][:gender]
    else
      @user.errors[:gender] << 'is required.'
    end

    if params[:user][:orientation] && !params[:user][:orientation].blank?
      @user.orientation=params[:user][:orientation]
    else
      @user.errors[:orientation] << 'is required.'
    end

    if params[:user][:zipcode] && !params[:user][:zipcode].blank?
      @user.zipcode=params[:user][:zipcode]
    else
      @user.errors[:zipcode] << 'is required.'
    end

    if params[:user][:profile_pic] && !params[:user][:zipcode].blank?
      @user.user_images.each do |ui|
        if ui.is_profile_pic
          ui.is_profile_pic=false
          ui.save
        end
      end
      @user.user_images.new(:photo=>params[:user][:profile_pic], :is_profile_pic=>true)
    end

    if params[:user]['birthdate(1i)'] && !params[:user]['birthdate(1i)'].blank?
      @user.birthdate=Date.new(params[:user]['birthdate(1i)'].to_i,params[:user]['birthdate(2i)'].to_i,params[:user]['birthdate(3i)'].to_i)
    else
      @user.errors[:birthdate] << 'is required.'
    end

    if @user.errors.count == 0 && @user.save
      redirect_to users_dashboards_path
    else
      render :index
    end

  end

end

app/controllers/users/messages_controller.rb
class Users::MessagesController < UsersController

  before_filter :get_mailbox, :get_box
  
  def index
    redirect_to conversations_path(:box => @box)
  end

  # GET /messages/1
  # GET /messages/1.xml
  def show
    if @message = Message.find_by_id(params[:id]) and @conversation = @message.conversation
      if @conversation.is_participant?(@actor)
        redirect_to conversation_path(@conversation, :box => @box, :anchor => "message_" + @message.id.to_s)
      return
      end
    end
    redirect_to conversations_path(:box => @box)
  end

  # GET /messages/new
  # GET /messages/new.xml
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit

  end

  # POST /messages
  # POST /messages.xml
  def create
    @recipients = Array.new
    if params[:_recipients].present?
      params[:_recipients].each do |recp_id|
        recp = Actor.find_by_id(recp_id)
        next if recp.nil?
        @recipients << recp
      end
    end
    @receipt = @actor.send_message(@recipients, params[:body], params[:subject])
    if (@receipt.errors.blank?)
      @conversation = @receipt.conversation
      flash[:success]= t('mailboxer.sent')
      redirect_to conversation_path(@conversation, :box => :sentbox)
    else
      render :action => :new
    end
  end

  # PUT /messages/1
  # PUT /messages/1.xml
  def update

  end

  # DELETE /messages/1
  # DELETE /messages/1.xml
  def destroy

  end
  
  def reply_to_conversation
    conversation = Conversation.find_by_id(params[:conversation_id])
    message_sent = current_user.reply_to_conversation(conversation, params[:message][:body])
    if message_sent
      redirect_to conversation_path(conversation)
    end
  end

  private

  def get_mailbox
    @mailbox = current_user.mailbox
  end

  # remove this
  def get_actor
    @actor = Actor.normalize(current_subject)
  end

  def get_box
    if params[:box].blank? or !["inbox","sentbox","trash"].include?params[:box]
      @box = "inbox"
    return
    end
    @box = params[:box]
  end

end

app/controllers/users/movies_controller.rb
class Users::MoviesController < UsersController

  def index
    @user=User.find(current_user.id)
    @watch_list=@user.watch_lists

    @param_miles=20
    @param_miles=params[:miles] if params[:miles] && !params[:miles].blank?
    @param_zip=@user.zipcode
    @param_zip=params[:zip] if params[:zip] && !params[:zip].blank?
    @param_search=nil
    @param_search=params[:search] if params[:search] && !params[:search].blank?

    # TODO: handle error for non-integer param

    # @movies=@zip.movies_and_theaters_near_zip(@param_miles)
    # commented out the version using ZipLoc (above) and opted for Movie Class method instead
    @movies = Movie.near(@param_zip, @param_miles, nil, @param_search)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: { 'movies' => @movies.to_json(:include => [:theaters ]) } }
    end
  end

  def show
    if params[:miles] && params[:zip]
      @movie = Movie.near(params[:zip], params[:miles], params[:id], nil).first
    else
      @movie = Movie.find(params[:id])
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie.to_json(:include=>[:theaters]) }
    end
  end

end

app/controllers/users/photos_controller.rb
class Users::PhotosController < UsersController

  def load_fb_images
    auth=@user.authentications.find_by_provider('facebook')
    #fb_user=FbGraph::User.me(auth.provider_auth_id).fetch

    album=FbGraph::User.me(auth.provider_auth_id).albums.detect do |album|
      album.type == 'profile'
    end
    @facebook_profile_pictures = album.photos

    logger.debug @facebook_profile_pictures.inspect
  end

  def index

    @user=User.find(current_user.id)

    # solo profile pic photo
    @profile_pic=@user.profile_pic

    # other photos
    @photos=@user.user_images.all(:conditions=>'is_profile_pic is null or is_profile_pic=false')

    logger.debug @photos.inspect

    @new_photo=UserImage.new(:user_id=>@user.id)

    load_fb_images

  end

  # post for new photo upload
  def create

    @user = User.find(current_user.id)

    load_fb_images

    # facebook upload
    if params[:user_image] && params[:user_image][:action]
      if params[:user_image][:action]=='import_facebook_profile_pictures'
        logger.debug 'Processing FB Image Load'

        @facebook_profile_pictures.each do |fb_pic|
          if params[:user_image][:picture_ids].include?(fb_pic.identifier)
            logger.debug 'Loading picture --- ' + fb_pic.inspect
            photo=@user.user_images.new()
            photo.picture_from_url(fb_pic.source)
          end
        end

        @user.save

      end
        @new_photo=UserImage.new(:user_id=>@user.id)
    else

      # regular upload -- form submission
      @new_photo=@user.user_images.new(params[:user_image])

      if @new_photo.is_profile_pic
        @user.user_images.each do |ui|
          (ui.is_profile_pic=false; ui.save) if ui.id && ui.is_profile_pic
        end
      end

      if @user.save
        @new_photo=UserImage.new(:user_id=>@user.id)
      end

    end

    @profile_pic=@user.profile_pic
    @photos=@user.user_images.all(:conditions=>'is_profile_pic is null or is_profile_pic=false')

    render :index

  end

  # used for setting specific image to 'is_profile_pic'
  def update

    @user = User.find(current_user.id)

    @photo=@user.user_images.find(params[:id])

    # hook into these actions
    if params[:user_image][:action]=='make_profile_picture'
      # turn off all the other ones.
      @user.user_images.each do |ui|
        (ui.is_profile_pic=false; ui.save) if ui.id && ui.is_profile_pic
      end

      @photo.is_profile_pic=true
      @photo.save
    end

    @profile_pic=@user.profile_pic
    @photos=@user.user_images.all(:conditions=>'is_profile_pic is null or is_profile_pic=false')
    @new_photo=UserImage.new(:user_id=>@user.id)

    load_fb_images

    render :index

  end

  # for deleting photos
  def destroy
    @user = User.find(current_user.id)

    @photo=@user.user_images.find(params[:id])

    @photo.destroy

    @profile_pic=@user.profile_pic
    @photos=@user.user_images.all(:conditions=>'is_profile_pic is null or is_profile_pic=false')
    @new_photo=UserImage.new(:user_id=>@user.id)

    load_fb_images

    render :index

  end

end

app/controllers/users/watch_lists_controller.rb
class Users::WatchListsController < UsersController

  # only implemented json handler
  def create
    uid=params[:user_id]
    movie_id=params[:movie_id]
    optional_note=params[:optional_note]
    watch_list_theaters=[]
    watch_list_theaters=params[:watch_list_theaters] if params[:watch_list_theaters]

    logger.debug(watch_list_theaters.include?("10"))

    # security - user can't add a movie to another user's watchlist
    unless current_user.id == uid.to_i
      render :json => { :success => false, :errors=>['not authorized'] }
      return
    end

    wl=WatchList.find_by_user_id_and_movie_id(uid,movie_id);
    wl.note = optional_note if wl

    wl=WatchList.new(:user_id=>uid, :movie_id=>movie_id, :note=>optional_note) unless wl

    respond_to do |format|
      format.html { # no implementation -- create view if needed
      }
      format.json {
        if wl.save
          wl.watch_list_preferred_theaters.each do |wlp|
            wlp.destroy unless watch_list_theaters.include?(wlp.theater_id.to_s)
          end
          watch_list_theaters.each do |theater_id|
            wl.watch_list_preferred_theaters.create(:theater_id=>theater_id)
          end

          render :json => { :success => true }
          return
        else
          render :json => {:success => false, :errors=>wl.errors }
          return
        end
      }
      end
  end

  def destroy
    uid=params[:user_id]
    movie_id=params[:movie_id]

    # TODO: same comment as above for security

    # make sure the watchlist item exists.
    wl=WatchList.find_by_user_id_and_movie_id(uid,movie_id)
    unless wl
      respond_to do |format|
        format.html { }
        format.json {
          render :json => { :success => false, :errors=>['not found'] }
          return
        }
      end
    end

    respond_to do |format|
      format.html { }
      format.json {
        if wl.destroy
          render :json => { :success => true }
          return
        else
          render :json => {:success => false, :errors=>wl.errors }
          return
        end
      }
    end

  end
end

app/helpers/users_helper.rb
module UsersHelper

  def age(dob)
    if dob
      now = Time.now.utc.to_date
      now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
    end
  end

end

app/views/users/profiles/_basic_info_modal.html.erb
<div id="modal_user_profile" class="modal" style="display:none">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    Edit your details.
  </div>
  <div class="modal-body">
    <%= form_for(@user, :url=>users_profile_path(@user.id), :html=>{:id=>'form_user_profile', :multipart=>true}) do |f| %>
      <%= f.label :firstname %>
      <%= f.text_field :firstname %>
      <%= f.label :gender %>
      <%= f.select :gender, options_for_select([["Female", 'female'],["Male", 'male']],  :selected=>@user.gender), { :include_blank=>true }%>
      <%= f.label :orientation %>
      <%= f.select :orientation, options_for_select([ ["Straight", "straight"], ["Gay/Lesbian", "gay"], ["Bisexual","bi"]], :selected=>@user.orientation),  { :include_blank=>true } %>
      <%= f.label :zipcode %>
      <%= f.text_field :zipcode %>
      <%= f.label :birthdate %>
      <%= f.date_select :birthdate %>
      <br/>
      <% if @user.errors.any? %>
        <ul id="form_user_profile_errors">
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      <% end %>
      <%= link_to raw('Save'), 'javascript:void(0);', :onclick=>"javascript:$('#form_user_profile').submit();", :remote=>true, :id=>'btn_submit_form_user_profile' %>
    <% end %>
  </div>
</div>

app/views/users/profiles/_modal_edit_watchlist.html.haml
.modal{:id => "watchlist_#{movie.id.to_s}",:style => 'display:none;', :class => "add-to-watch-list-modal"}
  .modal-header
    %a.close{'data-dismiss' =>"modal"} &times;
    %h3 Edit Watch List
  .modal-body
    %h3.title
      = movie.title
    .notes
      Optional Note (128 characters):
      %br/
      = text_field_tag 'optional_note', watchlist.note, :maxlength=>128, :style => "width:100%"
    .preferred_theaters
      %ul
        - watchlist.watch_list_preferred_theaters.each_with_index do |wpt,i|
          - if i % 2 == 1
            - margin_li = "20px"
            .clear
          - else
            - margin_li = "0px"
          %li{:style => "margin-right:#{margin_li}"}
            = check_box_tag 'watch_list_theaters', wpt.theater.id, true, :id => "watch_list_theater_#{wpt.theater.id}"
            = label_tag "watch_list_theater_#{wpt.theater.id}", wpt.theater.name

    .preferred_theaters
      Add Preferred theaters near:&nbsp;
      =text_field_tag 'preferred_theater_zip_code', @param_zip, :class => "span2"
      %a.refresh_preferred_theaters.btn.btn-primary{:movie_id=>"#{movie.id.to_s}"} Go
      %ul

  .modal-footer
    %a.watch-lists-add.btn.btn-primary.btn-large{:data_movie_id=>movie.id.to_s, :data_user_id=>current_user.id} Save
    %a.watch-lists-rem.btn.btn-primary.btn-large{:data_movie_id=>movie.id.to_s, :data_user_id=>current_user.id} Remove from Watch List

app/views/users/profiles/edit.html.haml
.row-fluid
  .span1
    %ul.thumbnails{:style => 'padding: 0px; margin-top:0px;'}
      %li.span1
        .thumbnail.nopadding
          != link_to(image_tag(@user.profile_pic.photo.url(:thumb)), users_photos_path) rescue '<img src="http://placehold.it/75x100" >'
  .span5
    %h3= @user.firstname
    %p
      = "#{@user.gender} / #{age(@user.birthdate)} / #{@user.orientation} / #{@user.zipcode}"
    %p
      %i.icon-camera
      = link_to(pluralize(@user.user_images.count, "picture"), users_photos_path)
    %p
      = link_to('Edit your details', '#', :onclick=>'show_modal("modal_user_profile");')

= render 'basic_info_modal'

%br
%br
.row-fluid
  .span9
    - if @user.watch_lists.count != 0
      .watchlists
        .header
          = @user.firstname
          is looking for buddies to see
        %br
        - @user.watch_lists.each do |w|
          .row-fluid
            .span2
              %ul.thumbnails{:style => 'padding: 0px; margin-top:0px;'}
                %li{:style => 'width: 75px; height: 100px;'}
                  .thumbnail.nopadding
                    = image_tag w.movie.poster.url, :class=>"mov_search_pic"
            .span6
              .description
                %h3= w.movie.title
                - if w.watch_list_preferred_theaters.count != 0
                  %p
                    %b Theaters:
                    - w.watch_list_preferred_theaters.each do |t|
                      = "#{t.theater.name} "
            .span4
              %span.btn-wrapper.pull-right
                = link_to('Edit Watchlist Item', 'javascript:void(0);', :onclick=>'javascript:show_modal("watchlist_' + w.movie_id.to_s + '");', :class => "btn btn-primary btn-large span2" )
                //= link_to("Let's Get Popcorn", {:controller => "users/conversations", :action => "new", :recipient_id => @user.id, :watch_list_id => w.id}, {:class => "btn btn-primary btn-large span2"})
          = render 'modal_edit_watchlist', :movie=>w.movie, :watchlist=>w

    %ul.questions-and-answer-portion
      - @questions.each do |q|
        %li
          .heading
            %h2= q.content
            .edit_link= link_to('(edit)', 'javascript:void(0);', :data=>q.id)
          - a=@user.answers.find_by_question_id(q.id)
          - if a
            .read_only{:id=>'read-only-' + q.id.to_s}
              = raw(a.response.gsub(/\n/, '<br>'))
            .edit{:id=>'edit-' + q.id.to_s}
              = form_for(a, :url=>users_answer_path(a.id), :remote=>true) do |f|
                = f.hidden_field :question_id
                = f.hidden_field :user_id
                = f.text_area :response, :rows=>3
                = f.submit
          - else
            - a=@user.answers.new(:question_id=>q.id, :user_id=>@user.id)
            .read_only{:id=>'read-only-' + q.id.to_s}
              = 'no answer'
            .edit{:id=>'edit-' + q.id.to_s}
              = form_for(a, :url=>users_answers_path, :remote=>true) do |f|
                = f.hidden_field :question_id
                = f.hidden_field :user_id
                = f.text_area :response, :rows=>3
                = f.submit


app/views/users/profiles/index.html.erb
<% # here i am going to insert the filter form based on the theater filter form %>
Buddies who want to see:
<%= select_tag('select_movie', options_for_select(@movies.collect { |m| [ m.title, m.id ] }.insert(0,['All Movies', 0]), @param_movie_id)) %>
within
<%= select_tag('select_miles', options_for_select(['1','5','10','20','50','100'], @param_miles )) %>
miles of
<%= text_field_tag :field_zip, @param_zip, :placeholder => @param_zip, :style => 'width: 90px;' %>
<%= submit_tag "Go", :class => 'search_filter btn btn-primary', :style => 'margin-top: -2px;'%>

<% @users.each do |user| %>
  <% ct=0 %>
  <% user.watch_lists.each do |wl| %>
    <% ct+=1 %>
    <% break if ct > 2 %>
    <div class="user_watch_list">
      <% if user.profile_pic %>
        <%= link_to(image_tag(user.profile_pic.photo.url(:medium), :class=>'buddy_search_profile_pic'), users_profile_path(user.id)) %>
      <% else %>
        -- No Image Replace with handler. --
      <% end %>
      <div class="watch_list_profile">
        <b><%= link_to(user.firstname, users_profile_path(user.id)) %></b>
        <br>
        <%= user.gender.camelize %>
        /
        <%= age(user.birthdate) %>
        /
        <%= user.orientation.camelize %>
        /
        <% #we still need to convert zip to manhattan neighborhood %>
        <%= user.zipcode%>
        <br>
        Looking for buddies to see:
        <br>
        <%= wl.movie.title %>
        <% if wl.watch_list_preferred_theaters.count > 0 %>
          at
          <%= wl.watch_list_preferred_theaters.first.theater.name %>
          <% if wl.watch_list_preferred_theaters.count > 1 %>
            and
            <%= link_to(pluralize(wl.watch_list_preferred_theaters.count - 1, 'more theater'), '#more_theaters_' + wl.id.to_s, 'data-toggle'=>'modal') %>.
            <div class='modal' id='more_theaters_<%= wl.id.to_s %>' style='display:none'>
              <div class='modal-header'>
                <%= link_to 'x', nil, :class=>'close', 'data-dismiss' => 'modal'%>
                <h3>Also wants to see at</h3>
              </div>
              <div class="modal-body">
                <ul>
                  <% wl.watch_list_preferred_theaters.each do |wlt| %>
                    <% unless wlt == wl.watch_list_preferred_theaters.first %>
                      <li><%= wlt.theater.name %></li>
                    <% end %>
                <% end %>
                </ul>
              </div>
            </div>
      <% end %>
        <% end %>
        <% if !wl.note.blank? %>
          <br>
          "<%= wl.note %>"
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

<% @other_users.each do |user|  %>
  <div class="user_watch_list">
    <% if user.profile_pic %>
      <%= link_to(image_tag(user.profile_pic.photo.url(:medium), :class=>'buddy_search_profile_pic'), users_profile_path(user.id)) %>
    <% else %>
      -- No Image Replace with handler. --
    <% end %>
    <div class="watch_list_profile">
      <b><%= link_to(user.firstname, users_profile_path(user.id)) %></b>
      <br>
      <%= user.gender.camelize %>
      /
      <%= age(user.birthdate) %>
      /
      <%= user.orientation.camelize %>
      /
      <% #we still need to convert zip to manhattan neighborhood %>
      <%= user.zipcode%>
      <br>
      No movies added to watch list.
    </div>
  </div>
<% end %>