config/routes.rb
Lgp::Application.routes.draw do

  # auth
  resources :authentications, :only=>[:create]
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/:provider' => 'authentications#show'


  # public
  resources :welcome, :only=>[:index]
  resources :invite_codes, :only=>[:create]
  resources :invite_requests, :only=>[:create]

  # user scoped
  devise_for :users
  namespace :users do
    resources :answers, :only => [ :create, :update ]
    resources :dashboards, :only => [ :index, :update ]
    # change message to be resource based route --- not match when implemented.
    #match "/messages" => "messages#message", :as=>"message"
    match 'conversations/update_preferred_theaters' => 'conversations#update_preferred_theaters', :via => [:get, :post]
    resources :conversations, :messages
    match "inbox" => "conversations#index"
    match "sentbox" => "conversations#sent"
    resources :movies, :only => [ :index, :show ]
    resources :photos, :only => [ :index, :create , :update, :destroy ]
    resources :profiles, :only => [ :index, :show, :edit, :update ]
    resources :watch_lists, :only => [ :create, :destroy ]
  end

  # admin scoped
  resources :admin, :only=>[:index]
  namespace :admin do
    resources :invite_codes
    resources :movies
    resources :questions
    resources :schedules
    resources :theaters
    resources :zip_locs
  end

  # default route
  root :to => 'welcome#index'
 
  match ':controller(/:action(/:id))'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout false

  def index
    @user=current_user
    @invite_code=InviteCode.new
    @invite_request=InviteRequest.new
    @signed_in=user_signed_in?

    if @signed_in
      redirect_to users_dashboards_path
    end

  end
  
end

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag    'application', :media => "all" %>
</head>
<body>
  <%= facebook_common 'FB_Callback();' %>
  
  <%= link_to 'Login', '/auth/facebook' %>

	<section>
		<div class="logotype"></div>

		<h2>Find a movie buddy today!</h2>

		<%= form_for(@invite_code, :url=>invite_codes_path(:format=>:json), :remote=> true, :html=>{:id => 'form_invite_code'}) do |f| %>
      <%= f.label :code, 'Invite Code:'%>
      <%= f.text_field :code %>
      <%= f.submit 'Get Popcorn!' %>
		<% end %>

    <ul id="errors"></ul>
    
	</section>

	<footer>
		Don't have an invite code? 
		<a href="javascript:void(0)">Use referrer e-mail address instead</a>
		or
    <%= link_to 'request an invite',  '#modal_request_invite', 'data-toggle'=>'modal' %>

	</footer>

  <script>
    // testing stuff for FB redirects

    function FB_Callback(){

      // for client side login form...
      FB.Event.subscribe('auth.login',
        function(response) {
          console.log('user just logged in');
          //FB_handle_login(response.authResponse.signedRequest, response.authResponse.accessToken)
          //window.location='/auth/facebook';
        }
      );

      FB.getLoginStatus(function(response) {
        console.log(response);

        // handles errors from server side auth controller.
        if (getUrlParam('error')){
          if (getUrlParam('error')=='invalid-invite'){
            show_modal('modal_request_invite');
          }
        } else if (response.status === 'connected') {
          console.log('user_logged into facebook -- app authorized');
          //alert('You visited the homepage and have already authorized the app in FB and are logged into FB -- what should we do? Redirecting for now.');
          //  window.location='/auth/facebook';
          //FB_handle_login(response.authResponse.signedRequest, response.authResponse.accessToken)
        } else if (response.status === 'not_authorized') {
          console.log('user_logged into facebook -- app not authorized');
          // the user is logged in to Facebook,
          // but has not authenticated your app
        } else {
          console.log('user not logged into facebook');
          // the user isn't logged in to Facebook.
        }
      });

    };

  </script>

  <div id="modal_request_invite" class="modal" style="display:none">
    <div class="modal-header">
      <a class="close" data-dismiss="modal">×</a>
      Request Beta Invite
    </div>
    <div class="modal-body">
      Lets Get Popcorn is available by invitation only
      Request an invite:
      <%= form_for(@invite_request, :url=>invite_requests_path(:format=>:json), :remote=>true, :html=>{:id=>'form_invite_request'}) do |f| %>
        <%= f.label :email %>
        <%= f.text_field :email %>
        <%= f.label :zip_code %>
        <%= f.text_field :zip_code %>
        <%= f.label :comments %>
        <%= f.text_area :comments, :rows=>5 %>
        <br/>
        <ul id="form_invite_request_errors"></ul>
        <%= f.submit 'Send Request' %>
      <% end %>
    </div>
  </div>

  <div id="modal_request_invite_success" class="modal" style="display:none">
    <div class="modal-header">
      <a class="close" data-dismiss="modal">×</a>
      Request Beta Invite
    </div>
    <div class="modal-body">
      Thanks for requesting access...
    </div>
  </div>

</body>
</html>

app/views/welcome/signup.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "welcome", :media => "all" %>
</head>
<body>

	<section>
		<div class="logotype"></div>

		<h2>Find a movie buddy today!</h2>
		
		<%= form_tag "/welcome/verify_code", {:id => 'invite_code'} do %>
			<label>Username: </label>
			<input type="text" placeholder="username" name="code_value" size="30" type="text" /><br/>
			<label>Password: </label>
			<input type="text" placeholder="Password" name="code_value"  size="30" type="text" /><br/>
			<label>Password (again): </label>
			<input type="text" placeholder="Password(again)" name="code_value"  size="30" type="text" /><br/>
			<label>Gender: </label>
			<%= select :user, :gender, options_for_select([["A Girl", "female"],["A Guy", "male"]]) %><br/>
			<label>Interested In: </label>
			<%= select :user, :orientation, options_for_select([["A Guy", "men"], ["A Girl", "women"], ["Any","any"]]) %><br/>
			<input type="submit" value="Register" />
		<%end%>

	</section>
		
</body>
</html>

app/views/welcome/verify_code.html.erb
<%=@results%>