config/routes.rb
Lgp::Application.routes.draw do

  # auth
  resources :authentications, :only=>[:create]
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/:provider' => 'authentications#show'


  # public
  resources :welcome, :only=>[:index]
  resources :invite_codes, :only=>[:create]
  resources :invite_requests, :only=>[:create]

  # user scoped
  devise_for :users
  namespace :users do
    resources :answers, :only => [ :create, :update ]
    resources :dashboards, :only => [ :index, :update ]
    # change message to be resource based route --- not match when implemented.
    #match "/messages" => "messages#message", :as=>"message"
    match 'conversations/update_preferred_theaters' => 'conversations#update_preferred_theaters', :via => [:get, :post]
    resources :conversations, :messages
    match "inbox" => "conversations#index"
    match "sentbox" => "conversations#sent"
    resources :movies, :only => [ :index, :show ]
    resources :photos, :only => [ :index, :create , :update, :destroy ]
    resources :profiles, :only => [ :index, :show, :edit, :update ]
    resources :watch_lists, :only => [ :create, :destroy ]
  end

  # admin scoped
  resources :admin, :only=>[:index]
  namespace :admin do
    resources :invite_codes
    resources :movies
    resources :questions
    resources :schedules
    resources :theaters
    resources :zip_locs
  end

  # default route
  root :to => 'welcome#index'
 
  match ':controller(/:action(/:id))'

end

app/controllers/users/answers_controller.rb
class Users::AnswersController < UsersController

  def create
    a=Answer.new(params[:answer])

    # security -- check user
    unless a.user_id == current_user.id
      render :json => { :success=>false, :errors=>['unauthorized']}
      return
    end

    if a.response.blank?
      render :json => { :success=> true, :question_id=>a.question_id, :new_response=>'' }
    else
      if a.save
        render :json => { :success=> true, :question_id=>a.question_id, :new_response=>a.response }
      else
        render :json => { :success=> false, :errors=>a.errors.to_json }
      end
    end


  end

  def update
    a=Answer.find(params[:id])

    # security -- check user
    unless a.user_id == current_user.id
      render :json => { :success=>false, :errors=>['unauthorized']}
      return
    end

    if params[:answer][:response].blank?
      qid=a.question_id
      a.destroy
      render :json => { :success=> true, :question_id=>qid, :new_response=>'' }
    else
      if a.update_attributes(params[:answer])
        render :json => { :success=> true, :question_id=>a.question_id, :new_response=>a.response }
      else
        render :json => { :success=> false, :errors=>a.errors.to_json }
      end
    end


  end

end

app/controllers/users/conversations_controller.rb
class Users::ConversationsController < UsersController

  before_filter :get_mailbox
  #before_filter :check_current_subject_in_conversation, :only => [:show, :update, :destroy]
  def index
    @conversations = @mailbox.inbox
    @mailbox_type = "inbox"
  end

  def show
    @message = Message.new
    @conversation = Conversation.where("id = ?", params[:id]).first
    @receipts = @conversation.receipts_for(current_user).order("created_at DESC")
    @receipts = remove_duplicate_receipts @receipts
    @recipient =  get_initial_recipient(@conversation)
    # check if there is a subject and therefore a movie title
    if @conversation.subject != "N/A"   #@TODO might want to change this later
      # get the movie object
      movie = Movie.find_by_title(@conversation.subject)
      # get the watchlist
      watch_list = WatchList.where("user_id = ? AND movie_id = ?", @recipient.id, movie.id).first
      #check for preferred theaters
      @preferred_theaters =  @recipient.watch_list_preferred_theaters(watch_list.id)
    end
  end

  def new
    if params[:recipient_id]
      @recipient = User.find_by_id(params[:recipient_id])
      @movies = @recipient.watchlist_movies
      if params[:watch_list_id]
        watch_list_item = WatchList.find(params[:watch_list_id])
        @default_movie = Movie.find(watch_list_item.movie_id)
        @preferred_theaters = @recipient.watch_list_preferred_theaters(watch_list_item.id)
      end
    end
  end

  def edit
    #@TODO if required
  end

  def create
    # verify everything
    recipient = User.find_by_id params[:recipient][:id]
    movie = Movie.find_by_id(params[:movie_id])
    body = params[:body][0]
    #@TODO add check here to make sure everything above is valid before sending message
    # create conversations e.g. send first message
    conversation = @current_user.send_message(recipient, body, movie.nil? ? "N/A" : movie.title )
    # return user to conversations page
    if conversation
      redirect_to users_conversations_path
    end
  end

  def sent
    @conversations = @mailbox.sentbox
    @mailbox_type = "sentbox"
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @conversation = @user.mailbox.conversations.where("conversation_id = ?", params[:format]).first
    @conversation.move_to_trash(@user)
    redirect_to users_inbox_path(@user)
  end

  def reply_to_conversation
    conversation = Conversation.find_by_id(params[:conversation][:id])
    message_sent = current_user.reply_to_conversation(conversation, params[:body][:body])
    if message_sent
      redirect_to users_conversation_path(conversation)
    end
  end

  def update_preferred_theaters
    @recipient = User.find_by_id(params[:user_id])
    watch_list = WatchList.where("user_id = ? AND movie_id = ?", @recipient.id, params[:movie_id]).first
    @preferred_theaters = @recipient.watch_list_preferred_theaters(watch_list.id)
    if @preferred_theaters
      respond_to do |format|
        format.js
      end
    end
  end

  private

  def get_mailbox
    @mailbox = current_user.mailbox
  end

  def get_actor
    @actor = Actor.normalize(current_user)
  end

  def get_box
    if params[:box].blank? or !["inbox","sentbox","trash"].include?params[:box]
      @box = "inbox"
    return
    end
    @box = params[:box]
  end

  def check_current_subject_in_conversation
    @conversation = Conversation.find_by_id(params[:id])

    if @conversation.nil? or !@conversation.is_participant?(@actor)
      redirect_to conversations_path(:box => @box)
    return
    end
  end

  def get_initial_recipient(conversation)
    # get last message receipt
    receipt = conversation.receipts.where("mailbox_type = ?", "inbox").order("created_at DESC").last
    # get receiving user
    user = User.find_by_id(receipt.receiver_id)
  end

  # if the user sends a message to themselves the first message will be repeated in both their inbox and outbox.
  # This removes that duplication.
  def remove_duplicate_receipts receipts
    size = receipts.size
    last = receipts[size-1]
    second_last = receipts[size-2]
    # check if they are the same
    if last.message == second_last.message
      receipts.pop
    end
    receipts
  end
end

app/controllers/users/dashboards_controller.rb
class Users::DashboardsController < UsersController

  def index
    @user=User.find(current_user.id)
    @near_buddies = @user.near_buddies
    @popular_movies = Movie.popular(@user.zipcode)
  end

  # processes second registration step for user
  def update
    @user=User.find(params[:id])

    # security check
    unless @user.id==current_user.id
      @user.errors[:firstname] << 'you do not have permission to do this'
      return
    end

    # fields we are allowed to update, with custom errors if not present...
    if params[:user][:firstname] && !params[:user][:firstname].blank?
      @user.firstname=params[:user][:firstname]
    else
      @user.errors[:firstname] << 'is required.'
    end

    if params[:user][:gender] && !params[:user][:gender].blank?
      @user.gender=params[:user][:gender]
    else
      @user.errors[:gender] << 'is required.'
    end

    if params[:user][:orientation] && !params[:user][:orientation].blank?
      @user.orientation=params[:user][:orientation]
    else
      @user.errors[:orientation] << 'is required.'
    end

    if params[:user][:zipcode] && !params[:user][:zipcode].blank?
      @user.zipcode=params[:user][:zipcode]
    else
      @user.errors[:zipcode] << 'is required.'
    end

    if params[:user][:profile_pic] && !params[:user][:zipcode].blank?
      @user.user_images.each do |ui|
        if ui.is_profile_pic
          ui.is_profile_pic=false
          ui.save
        end
      end
      @user.user_images.new(:photo=>params[:user][:profile_pic], :is_profile_pic=>true)
    end

    if params[:user]['birthdate(1i)'] && !params[:user]['birthdate(1i)'].blank?
      @user.birthdate=Date.new(params[:user]['birthdate(1i)'].to_i,params[:user]['birthdate(2i)'].to_i,params[:user]['birthdate(3i)'].to_i)
    else
      @user.errors[:birthdate] << 'is required.'
    end

    if @user.errors.count == 0 && @user.save
      redirect_to users_dashboards_path
    else
      render :index
    end

  end

end

app/controllers/users/messages_controller.rb
class Users::MessagesController < UsersController

  before_filter :get_mailbox, :get_box
  
  def index
    redirect_to conversations_path(:box => @box)
  end

  # GET /messages/1
  # GET /messages/1.xml
  def show
    if @message = Message.find_by_id(params[:id]) and @conversation = @message.conversation
      if @conversation.is_participant?(@actor)
        redirect_to conversation_path(@conversation, :box => @box, :anchor => "message_" + @message.id.to_s)
      return
      end
    end
    redirect_to conversations_path(:box => @box)
  end

  # GET /messages/new
  # GET /messages/new.xml
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit

  end

  # POST /messages
  # POST /messages.xml
  def create
    @recipients = Array.new
    if params[:_recipients].present?
      params[:_recipients].each do |recp_id|
        recp = Actor.find_by_id(recp_id)
        next if recp.nil?
        @recipients << recp
      end
    end
    @receipt = @actor.send_message(@recipients, params[:body], params[:subject])
    if (@receipt.errors.blank?)
      @conversation = @receipt.conversation
      flash[:success]= t('mailboxer.sent')
      redirect_to conversation_path(@conversation, :box => :sentbox)
    else
      render :action => :new
    end
  end

  # PUT /messages/1
  # PUT /messages/1.xml
  def update

  end

  # DELETE /messages/1
  # DELETE /messages/1.xml
  def destroy

  end
  
  def reply_to_conversation
    conversation = Conversation.find_by_id(params[:conversation_id])
    message_sent = current_user.reply_to_conversation(conversation, params[:message][:body])
    if message_sent
      redirect_to conversation_path(conversation)
    end
  end

  private

  def get_mailbox
    @mailbox = current_user.mailbox
  end

  # remove this
  def get_actor
    @actor = Actor.normalize(current_subject)
  end

  def get_box
    if params[:box].blank? or !["inbox","sentbox","trash"].include?params[:box]
      @box = "inbox"
    return
    end
    @box = params[:box]
  end

end

app/controllers/users/movies_controller.rb
class Users::MoviesController < UsersController

  def index
    @user=User.find(current_user.id)
    @watch_list=@user.watch_lists

    @param_miles=20
    @param_miles=params[:miles] if params[:miles] && !params[:miles].blank?
    @param_zip=@user.zipcode
    @param_zip=params[:zip] if params[:zip] && !params[:zip].blank?
    @param_search=nil
    @param_search=params[:search] if params[:search] && !params[:search].blank?

    # TODO: handle error for non-integer param

    # @movies=@zip.movies_and_theaters_near_zip(@param_miles)
    # commented out the version using ZipLoc (above) and opted for Movie Class method instead
    @movies = Movie.near(@param_zip, @param_miles, nil, @param_search)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: { 'movies' => @movies.to_json(:include => [:theaters ]) } }
    end
  end

  def show
    if params[:miles] && params[:zip]
      @movie = Movie.near(params[:zip], params[:miles], params[:id], nil).first
    else
      @movie = Movie.find(params[:id])
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie.to_json(:include=>[:theaters]) }
    end
  end

end

app/controllers/users/photos_controller.rb
class Users::PhotosController < UsersController

  def load_fb_images
    auth=@user.authentications.find_by_provider('facebook')
    #fb_user=FbGraph::User.me(auth.provider_auth_id).fetch

    album=FbGraph::User.me(auth.provider_auth_id).albums.detect do |album|
      album.type == 'profile'
    end
    @facebook_profile_pictures = album.photos

    logger.debug @facebook_profile_pictures.inspect
  end

  def index

    @user=User.find(current_user.id)

    # solo profile pic photo
    @profile_pic=@user.profile_pic

    # other photos
    @photos=@user.user_images.all(:conditions=>'is_profile_pic is null or is_profile_pic=false')

    logger.debug @photos.inspect

    @new_photo=UserImage.new(:user_id=>@user.id)

    load_fb_images

  end

  # post for new photo upload
  def create

    @user = User.find(current_user.id)

    load_fb_images

    # facebook upload
    if params[:user_image] && params[:user_image][:action]
      if params[:user_image][:action]=='import_facebook_profile_pictures'
        logger.debug 'Processing FB Image Load'

        @facebook_profile_pictures.each do |fb_pic|
          if params[:user_image][:picture_ids].include?(fb_pic.identifier)
            logger.debug 'Loading picture --- ' + fb_pic.inspect
            photo=@user.user_images.new()
            photo.picture_from_url(fb_pic.source)
          end
        end

        @user.save

      end
        @new_photo=UserImage.new(:user_id=>@user.id)
    else

      # regular upload -- form submission
      @new_photo=@user.user_images.new(params[:user_image])

      if @new_photo.is_profile_pic
        @user.user_images.each do |ui|
          (ui.is_profile_pic=false; ui.save) if ui.id && ui.is_profile_pic
        end
      end

      if @user.save
        @new_photo=UserImage.new(:user_id=>@user.id)
      end

    end

    @profile_pic=@user.profile_pic
    @photos=@user.user_images.all(:conditions=>'is_profile_pic is null or is_profile_pic=false')

    render :index

  end

  # used for setting specific image to 'is_profile_pic'
  def update

    @user = User.find(current_user.id)

    @photo=@user.user_images.find(params[:id])

    # hook into these actions
    if params[:user_image][:action]=='make_profile_picture'
      # turn off all the other ones.
      @user.user_images.each do |ui|
        (ui.is_profile_pic=false; ui.save) if ui.id && ui.is_profile_pic
      end

      @photo.is_profile_pic=true
      @photo.save
    end

    @profile_pic=@user.profile_pic
    @photos=@user.user_images.all(:conditions=>'is_profile_pic is null or is_profile_pic=false')
    @new_photo=UserImage.new(:user_id=>@user.id)

    load_fb_images

    render :index

  end

  # for deleting photos
  def destroy
    @user = User.find(current_user.id)

    @photo=@user.user_images.find(params[:id])

    @photo.destroy

    @profile_pic=@user.profile_pic
    @photos=@user.user_images.all(:conditions=>'is_profile_pic is null or is_profile_pic=false')
    @new_photo=UserImage.new(:user_id=>@user.id)

    load_fb_images

    render :index

  end

end

app/controllers/users/watch_lists_controller.rb
class Users::WatchListsController < UsersController

  # only implemented json handler
  def create
    uid=params[:user_id]
    movie_id=params[:movie_id]
    optional_note=params[:optional_note]
    watch_list_theaters=[]
    watch_list_theaters=params[:watch_list_theaters] if params[:watch_list_theaters]

    logger.debug(watch_list_theaters.include?("10"))

    # security - user can't add a movie to another user's watchlist
    unless current_user.id == uid.to_i
      render :json => { :success => false, :errors=>['not authorized'] }
      return
    end

    wl=WatchList.find_by_user_id_and_movie_id(uid,movie_id);
    wl.note = optional_note if wl

    wl=WatchList.new(:user_id=>uid, :movie_id=>movie_id, :note=>optional_note) unless wl

    respond_to do |format|
      format.html { # no implementation -- create view if needed
      }
      format.json {
        if wl.save
          wl.watch_list_preferred_theaters.each do |wlp|
            wlp.destroy unless watch_list_theaters.include?(wlp.theater_id.to_s)
          end
          watch_list_theaters.each do |theater_id|
            wl.watch_list_preferred_theaters.create(:theater_id=>theater_id)
          end

          render :json => { :success => true }
          return
        else
          render :json => {:success => false, :errors=>wl.errors }
          return
        end
      }
      end
  end

  def destroy
    uid=params[:user_id]
    movie_id=params[:movie_id]

    # TODO: same comment as above for security

    # make sure the watchlist item exists.
    wl=WatchList.find_by_user_id_and_movie_id(uid,movie_id)
    unless wl
      respond_to do |format|
        format.html { }
        format.json {
          render :json => { :success => false, :errors=>['not found'] }
          return
        }
      end
    end

    respond_to do |format|
      format.html { }
      format.json {
        if wl.destroy
          render :json => { :success => true }
          return
        else
          render :json => {:success => false, :errors=>wl.errors }
          return
        end
      }
    end

  end
end

app/helpers/users_helper.rb
module UsersHelper

  def age(dob)
    if dob
      now = Time.now.utc.to_date
      now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
    end
  end

end

app/views/users/dashboards/_dashboard_movie_synopsis.html.haml
.movie.movie_synopsis_lists
  = link_to image_tag(movie.poster, class: 'movie_thumb'), "#summary_#{movie.id.to_s}", :'data-toggle' => "modal"
  .description
    = link_to movie.title, "#summary_#{movie.id.to_s}", :'data-toggle' => "modal"
    %br/

    = movie.rating
    %br/

    .span2.watchlist-action{'class' => (current_user.watch_lists.select{|x| x.movie_id == movie.id}.count != 0 ? 'is_watched' : ''), 'data-movie-id' => movie.id, 'data-user-id' => current_user.id, :style => "margin:5px 0 12px 0"}
      %a.watch-lists-rem.btn.btn-primary{:data_movie_id=>movie.id.to_s, :data_user_id=>current_user.id} Remove
      = link_to "Add to Watch List", '#watchlist_'+ movie.id.to_s, 'data-toggle'=>'modal', :class=>'watch-lists-add-display btn btn-primary'
      = render partial: 'users/movies/modal_add_to_watchlist', locals: { movie: movie }
      = render partial: "users/movies/modal_movie_summary", locals: { movie: movie }

    %p
      - watchlisters = []
      - movie.watchlisters.all.each do |w|
        - if w.id != current_user.id
          - watchlisters.push(w)
      - watchlisters[0..4].each do |w|
        - if w.id != current_user.id
          = link_to users_profiles_path(w.id) do
            %img{:src => (w.user_images.first(:order=>'id desc', :conditions=>'is_profile_pic=true').photo.url(:medium) rescue "/assets/bw_popcorn_kernel.jpg"), :class => "user_small_thumb" }
    %br/
    - if watchlisters.count != 0
      %p
        %a.purple{:href => users_profiles_path(watchlisters.first.id)}= watchlisters.first.firstname
        - if watchlisters.size == 1
          wants to see this
        - if watchlisters.count > 1
          and
          = watchlisters.count - 1
          other people near you want to see this (
          %a see all
          )

%br/

app/views/users/dashboards/_dashboard_user_synopsis.html.haml
.buddy
  = image_tag((buddy.profile_pic.photo(:thumb) rescue "bw_popcorn_kernel.jpg"), class: "user_thumb")
  = link_to buddy.firstname, users_profile_path(buddy)
  = "#{age(buddy.birthdate)} / #{buddy.gender.humanize} / #{buddy.orientation && buddy.orientation.humanize || '-'} / #{buddy.zipcode}"
  - if buddy.watch_lists.last
    %br/
    Wants to see:
    = '"' + buddy.watch_lists.last.movie.title + '"'
  %br/
  - if buddy.answers.count > 0
    - answer = buddy.answers.sample(1).first
    - question = answer.question
    = question.content
    = '"' + answer.response + '"'
%br/

app/views/users/dashboards/index.html.erb
<% unless @user.firstname && @user.gender && @user.orientation && @user.zipcode && @user.birthdate %>
  <div id="modal_user_profile" class="modal" style="display:none">
    <div class="modal-header">
      Almost There!
    </div>
    <div class="modal-body">
      <%= form_for(@user, :url=>users_dashboard_path(@user.id), :html=>{:id=>'form_user_profile', :multipart=>true}) do |f| %>
        <%= f.label :firstname %>
        <%= f.text_field :firstname %>
        <%= f.label :gender %>
        <%= f.select :gender, options_for_select([["Female", 'female'],["Male", 'male']],  :selected=>@user.gender), { :include_blank=>true }%>
        <%= f.label :orientation %>
        <%= f.select :orientation, options_for_select([ ["Straight", "straight"], ["Gay/Lesbian", "gay"], ["Bisexual","bi"]], :selected=>@user.orientation),  { :include_blank=>true } %>
        <%= f.label :zipcode %>
        <%= f.text_field :zipcode %>
        <%= f.label :birthdate %>
        <%= f.date_select :birthdate %>
        <br/>
        <%= image_tag @user.profile_pic.photo(:thumb) if @user.profile_pic %>
        Upload a different picture
        <%= f.file_field :profile_pic %>
        <br/>
        <ul id="form_user_profile_errors">
        <% if @user.errors.any? %>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        <% end %>
        </ul>
        <%= link_to raw('Finish Signup'), 'javascript:void(0);', :onclick=>"javascript:submit_profile_form();", :remote=>true, :id=>'btn_submit_form_user_profile' %>
      <% end %>
    </div>
  </div>
  <div id="modal_user_profile_exists" exists=1></div>
<% end %>

<header class="sub_head">
  <h2>Welcome to Let's Get Popcorn!
    <%= form_tag users_movies_path, :method => :get do -%>
      <%= submit_tag "Search", :class => 'search_filter btn btn-primary' -%>
      <%= text_field_tag :field_search, @param_search, :style => 'width: 150px;float:right;' -%>
      <%= label_tag :field_search, "Search Movies:" -%>
    <%- end -%>
  </h2>
  <!-- clear the float -->
  <div class="clearfloat"></div>
</header>

<div class="row-fluid">
  <div class="buddies_near_you span5">
    <h3>
      Popcorn Buddies near you
      (<%= link_to "browse all", users_profiles_path, class: "deco" %>):
    </h3>
    <%= render partial: 'dashboard_user_synopsis', collection: @near_buddies, as: :buddy -%>
  </div><!-- .buddies_near_you -->

  <div class="popular_movies span5">
    <div class="alert alert-info" data-dismiss='alert'>
      <a class="close" href="#">x</a>
      <center><b>
        Add a movie to your watchlist
        today and start connecting with
        nearby moviegoers!
        </b></center>
      
    </div>
    <!-- .cta -->
    <h3>
      Popular Movies:
      (<%= link_to "browse all", users_movies_path, class: "deco" %>):
    </h3>
    <%= render partial: "dashboard_movie_synopsis", collection: @popular_movies, as: :movie -%>
  </div><!-- .popular_movies -->

  <div class="sidebar span2">
    <h3>Recent Reviews:</h3>
    <div class="recent_reviews">
      <% 2.times do |num| %>
        <%= link_to "John", "#" %> reviewed
        <%= link_to "Horrible Bosses", "#", class: "deco" %>
        <br />
      <% end %>
    </div><!-- .recent_reviews -->

    <br />

    <h3>Your Visitors:</h3>
    <%- User.all.sample(4).each do |u| -%>
      <div class="visitor">
        <%= image_tag((u.profile_pic.photo(:small_thumb) rescue "bw_popcorn_kernel.jpg"), :class => "user_small_thumb") -%>
        <div class="description">
          <%= link_to u.firstname, "#" -%>
          <br />
          <p> <%= "#{age(u.birthdate)} / #{u.gender.humanize}" -%> </p>
        </div>
      </div>
    <% end %>
    <!-- .your_visitors -->
  </div>
</div>