config/routes.rb
Lgp::Application.routes.draw do

  # auth
  resources :authentications, :only=>[:create]
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/:provider' => 'authentications#show'


  # public
  resources :welcome, :only=>[:index]
  resources :invite_codes, :only=>[:create]
  resources :invite_requests, :only=>[:create]

  # user scoped
  devise_for :users
  namespace :users do
    resources :answers, :only => [ :create, :update ]
    resources :dashboards, :only => [ :index, :update ]
    # change message to be resource based route --- not match when implemented.
    #match "/messages" => "messages#message", :as=>"message"
    match 'conversations/update_preferred_theaters' => 'conversations#update_preferred_theaters', :via => [:get, :post]
    resources :conversations, :messages
    match "inbox" => "conversations#index"
    match "sentbox" => "conversations#sent"
    resources :movies, :only => [ :index, :show ]
    resources :photos, :only => [ :index, :create , :update, :destroy ]
    resources :profiles, :only => [ :index, :show, :edit, :update ]
    resources :watch_lists, :only => [ :create, :destroy ]
  end

  # admin scoped
  resources :admin, :only=>[:index]
  namespace :admin do
    resources :invite_codes
    resources :movies
    resources :questions
    resources :schedules
    resources :theaters
    resources :zip_locs
  end

  # default route
  root :to => 'welcome#index'
 
  match ':controller(/:action(/:id))'

end

app/models/invite_code.rb
class InviteCode < ActiveRecord::Base
  has_many :users
  validates_presence_of :code
  validates_uniqueness_of :code
end

app/controllers/admin/invite_codes_controller.rb
class Admin::InviteCodesController < AdminController

  def index
    @invite_codes=InviteCode.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invite_codes }
    end
  end

  def show
    @invite_code = InviteCode.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invite_code }
    end
  end

  def new
    @invite_code = InviteCode.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invite_code }
    end
  end

  def edit
    @invite_code = InviteCode.find(params[:id])
  end

  def create
    @invite_code = InviteCode.new(params[:invite_code])

    respond_to do |format|
      if @invite_code.save
        format.html { redirect_to admin_invite_code_path(@invite_code), notice: 'Invite Code was successfully created.' }
        format.json { render json: @invite_code, status: :created, location: @invite_code }
      else
        format.html { render action: "new" }
        format.json { render json: @invite_code.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @invite_code = InviteCode.find(params[:id])

    respond_to do |format|
      if @invite_code.update_attributes(params[:invite_code])
        format.html { redirect_to admin_invite_code_path(@invite_code), notice: 'Invite Code was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @invite_code.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @invite_code=InviteCode.find(params[:id])
    @invite_code.destroy

    respond_to do |format|
      format.html { redirect_to admin_invite_codes_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/invite_codes_controller.rb
class InviteCodesController < ApplicationController

  # use this method to check if code is valid
  def create
    unless params[:invite_code] && params[:invite_code][:code] && !params[:invite_code][:code].blank?
      render :json => { :success=> false, :errors=>['invite code is required']}
      return
    end

    if(InviteCode.find_by_code(params[:invite_code][:code]))
      cookies[:invite_code]=params[:invite_code][:code]
      render :json => { :success=>true, :message=>'valid invite code', :errors=>[] }
    else
      render :json => { :success=>false, :errors=>['invalid invite code'] }
    end
  end

end

app/views/admin/invite_codes/_form.html.erb
<% url=(@invite_code.id ? admin_invite_code_path(@invite_code) : admin_invite_codes_path ) %>
<%= form_for(@invite_code, :url=>url) do |f| %>
  <% if @invite_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invite_code.errors.count, "error") %> prohibited this invite code from being saved:</h2>

      <ul>
      <% @invite_code.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :audience %><br />
    <%= f.text_field :audience %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/invite_codes/edit.html.erb
<h1>Editing invite code</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_invite_code_path(@invite_code) %> |
<%= link_to 'Back', admin_invite_codes_path %>

app/views/admin/invite_codes/index.html.erb
<h1>Listing Invite Codes</h1>
<%=  link_to 'New Invite Code', new_admin_invite_code_path %>
<table border=1>
  <tr>
    <th>Code</th>
    <th>Active?</th>
    <th>Audience</th>
    <th>Comment</th>
    <th></th>
    <th></th>
  </tr>

<% @invite_codes.each do |c| %>
  <tr>
    <td><%= link_to c.code, admin_invite_code_path(c) %></td>
    <td><%= c.active %></td>
    <td><%= c.audience %></td>
    <td><%= c.comment %></td>
    <td><%= link_to 'Edit', edit_admin_invite_code_path(c) %></td>
    <td><%= link_to 'Delete', admin_invite_code_path(c), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/admin/invite_codes/new.html.erb
<h1>New invite code</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_invite_codes_path %>

app/views/admin/invite_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @invite_code.code %>
</p>

<p>
  <b>Active:</b>
  <%= @invite_code.active %>
</p>

<p>
  <b>Audience:</b>
  <%= @invite_code.audience %>
</p>

<p>
  <b>Comment:</b>
  <%= @invite_code.comment %>
</p>

<%= link_to 'Edit', edit_admin_invite_code_path(@invite_code) %> |
<%= link_to 'Back', admin_invite_codes_path %>